### ISSUE TITLE
issue with starting up on ububtu aws container

### ISSUE THREAD

**Issue by rkiddy** [18F/snap-js-prescreener-prototypes#52]
Hello -
I tried to take this project, install it on an aws container, run it and I was hoping that I could then see the web output and see what was being offered. Maybe with a basic set of dummy data? This rarely works with any project I try, but I keep trying and hoping it will. Someday.

What I did was:
- create a ubuntu AMI, middle size, standard defaults
- install npm (and I am _not_ a node expect, by the way)
- clone the repo
- try to run

You can see the result in the log I will add below.

The error may not be a problem with this project. But if it is possible to make the server work for this use case, it might be a good thing. Let me know if I can assist in any way.

thanx - ray

wow. the default formatting on ubuntu logs looks not too bad...

`% ssh -i .ssh/(my).pem ubuntu@54.203.199.236
The authenticity of host '54.203.199.236 (54.203.199.236)' can't be established.
ECDSA key fingerprint is SHA256:firMby3rmxitj8utCyyPICSIBm4+GARPuwKZj4UjZjc.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '54.203.199.236' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1111-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

$ 
$ sudo sh
# 
# apt-get update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7,532 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]     
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial/universe Translation-en [4,354 kB]  
Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]   
Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:9 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,184 kB]
Get:10 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [444 kB]
Get:11 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [803 kB]
Get:12 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [337 kB]
Get:13 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [17.1 kB]
Get:14 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8,632 B]
Get:15 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7,280 B]
Get:16 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4,456 B]
Get:17 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8,316 B]
Get:18 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4,476 B]
Get:19 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [907 kB]        
Get:20 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [338 kB]
Get:21 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [500 kB]
Get:22 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [206 kB]
Get:23 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [6,084 B]
Get:24 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [2,888 B]
Fetched 17.2 MB in 3s (5,680 kB/s)                           
Reading package lists... Done
# 

# apt-get install curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.15).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
# exit
$ 
$ 
$ curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease               
Reading package lists... 9% 
Reading package lists... Done

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/xenial/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb https://deb.nodesource.com/node_14.x xenial main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_14.x xenial main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 https://deb.nodesource.com/node_14.x xenial InRelease [4,584 B]           
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease               
Get:6 https://deb.nodesource.com/node_14.x xenial/main amd64 Packages [762 B]
Fetched 5,346 B in 0s (14.9 kB/s)                         
Reading package lists... Done

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

$ 
$ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python python-minimal python2.7 python2.7-minimal
Suggested packages:
  python-doc python-tk python2.7-doc binutils binfmt-support
The following NEW packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib nodejs python python-minimal python2.7 python2.7-minimal
0 upgraded, 8 newly installed, 0 to remove and 13 not upgraded.
Need to get 28.7 MB of archives.
After this operation, 136 MB of additional disk space will be used.
Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython2.7-minimal amd64 2.7.12-1ubuntu0~16.04.12 [338 kB]
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python2.7-minimal amd64 2.7.12-1ubuntu0~16.04.12 [1,258 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python-minimal amd64 2.7.12-1~16.04 [28.1 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython2.7-stdlib amd64 2.7.12-1ubuntu0~16.04.12 [1,883 kB]
Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python2.7 amd64 2.7.12-1ubuntu0~16.04.12 [224 kB]
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython-stdlib amd64 2.7.12-1~16.04 [7,768 B]
Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python amd64 2.7.12-1~16.04 [137 kB]
Get:8 https://deb.nodesource.com/node_14.x xenial/main amd64 nodejs amd64 14.8.0-1nodesource1 [24.8 MB]
Fetched 28.7 MB in 0s (43.7 MB/s)
Selecting previously unselected package libpython2.7-minimal:amd64.
(Reading database ... 51436 files and directories currently installed.)
Preparing to unpack .../libpython2.7-minimal_2.7.12-1ubuntu0~16.04.12_amd64.deb ...
Unpacking libpython2.7-minimal:amd64 (2.7.12-1ubuntu0~16.04.12) ...
Selecting previously unselected package python2.7-minimal.
Preparing to unpack .../python2.7-minimal_2.7.12-1ubuntu0~16.04.12_amd64.deb ...
Unpacking python2.7-minimal (2.7.12-1ubuntu0~16.04.12) ...
Selecting previously unselected package python-minimal.
Preparing to unpack .../python-minimal_2.7.12-1~16.04_amd64.deb ...
Unpacking python-minimal (2.7.12-1~16.04) ...
Selecting previously unselected package libpython2.7-stdlib:amd64.
Preparing to unpack .../libpython2.7-stdlib_2.7.12-1ubuntu0~16.04.12_amd64.deb ...
Unpacking libpython2.7-stdlib:amd64 (2.7.12-1ubuntu0~16.04.12) ...
Selecting previously unselected package python2.7.
Preparing to unpack .../python2.7_2.7.12-1ubuntu0~16.04.12_amd64.deb ...
Unpacking python2.7 (2.7.12-1ubuntu0~16.04.12) ...
Selecting previously unselected package libpython-stdlib:amd64.
Preparing to unpack .../libpython-stdlib_2.7.12-1~16.04_amd64.deb ...
Unpacking libpython-stdlib:amd64 (2.7.12-1~16.04) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up libpython2.7-minimal:amd64 (2.7.12-1ubuntu0~16.04.12) ...
Setting up python2.7-minimal (2.7.12-1ubuntu0~16.04.12) ...
Linking and byte-compiling packages for runtime python2.7...
Setting up python-minimal (2.7.12-1~16.04) ...
Selecting previously unselected package python.
(Reading database ... 52182 files and directories currently installed.)
Preparing to unpack .../python_2.7.12-1~16.04_amd64.deb ...
Unpacking python (2.7.12-1~16.04) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_14.8.0-1nodesource1_amd64.deb ...
Unpacking nodejs (14.8.0-1nodesource1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libpython2.7-stdlib:amd64 (2.7.12-1ubuntu0~16.04.12) ...
Setting up python2.7 (2.7.12-1ubuntu0~16.04.12) ...
Setting up libpython-stdlib:amd64 (2.7.12-1~16.04) ...
Setting up python (2.7.12-1~16.04) ...
Setting up nodejs (14.8.0-1nodesource1) ...
$ 
$ 
$ 
$ git clone https://github.com/rkiddy/snap-js-prescreener-prototypes.git
Cloning into 'snap-js-prescreener-prototypes'...
remote: Enumerating objects: 245, done.
remote: Counting objects: 100% (245/245), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 1490 (delta 103), reused 193 (delta 71), pack-reused 1245
Receiving objects: 100% (1490/1490), 5.26 MiB | 0 bytes/s, done.
Resolving deltas: 100% (644/644), done.
Checking connectivity... done.
$ 
$ 
$ cd snap-js-prescreener-prototypes/
/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$ npm run build

> snap-js-prescreener-prototypes@0.0.1 build /home/ubuntu/snap-js-prescreener-prototypes
> npx webpack --config webpack.config.js

npx: installed 344 in 12.687s
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...

> puppeteer@1.20.0 install /home/ubuntu/snap-js-prescreener-prototypes/node_modules/pa11y/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/ubuntu/snap-js-prescreener-prototypes/node_modules/pa11y/node_modules/puppeteer/.local-chromium/linux-686378

> puppeteer@4.0.0 install /home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer
> node install.js

Downloading Chromium r756035 - 125.2 Mb [====================] 100% 0.0s 
Chromium (756035) downloaded to /home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/.local-chromium/linux-756035

> core-js@3.6.5 postinstall /home/ubuntu/snap-js-prescreener-prototypes/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack-cli@3.3.12
added 976 packages from 483 contributors and audited 982 packages in 30.439s

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Cannot find module 'webpack-cli'
Require stack:
- /home/ubuntu/.npm/_npx/3674/lib/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at /home/ubuntu/.npm/_npx/3674/lib/node_modules/webpack/bin/webpack.js:143:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/.npm/_npx/3674/lib/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snap-js-prescreener-prototypes@0.0.1 build: `npx webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snap-js-prescreener-prototypes@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-08-17T17_25_29_215Z-debug.log
/snap-js-prescreener-prototypes$ cd ..
$ 

#### AT THIS POINT, I FOUND: https://github.com/webpack/webpack-cli/issues/436

$ npm rm -g webpack-cli
up to date in 0.038s
$ 
$ cd snap-js-prescreener-prototypes/
/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$  npm i -D webpack-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack-cli@3.3.12
updated 1 package and audited 982 packages in 5.939s

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$ npm run build

> snap-js-prescreener-prototypes@0.0.1 build /home/ubuntu/snap-js-prescreener-prototypes
> npx webpack --config webpack.config.js

Hash: f7a5607b80a1927a36da
Version: webpack 4.43.0
Time: 1088ms
Built at: 08/17/2020 5:28:44 PM
                  Asset      Size  Chunks             Chunk Names
form-controls.bundle.js  8.72 KiB       0  [emitted]  main
Entrypoint main = form-controls.bundle.js
[0] ./prescreeners/form-controls.js 15.5 KiB {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$ 
/snap-js-prescreener-prototypes$ npm run pa11y

> snap-js-prescreener-prototypes@0.0.1 pa11y /home/ubuntu/snap-js-prescreener-prototypes
> pa11y-ci ./prescreeners/il.html && pa11y-ci ./prescreeners/va.html

(node:3810) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/lib/launcher/BrowserRunner.js:189:20)
    at Interface.<anonymous> (/home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/lib/launcher/BrowserRunner.js:179:65)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3810) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3822) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/lib/launcher/BrowserRunner.js:189:20)
    at Interface.<anonymous> (/home/ubuntu/snap-js-prescreener-prototypes/node_modules/puppeteer/lib/launcher/BrowserRunner.js:179:65)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3822) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3822) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/snap-js-prescreener-prototypes$ 
`

**Comment by alexsoble** [comment]
Hi @rkiddy! If you are using AWS, then S3 might be a simpler way to run this project, since it consists only of flat files. A full Ubuntu AWS container won't be needed. For example, the preview site for this project is running on Federalist, which currently uses S3 under the hood: https://federalist.18f.gov/documentation/how-federalist-works/.

Thanks for your interest in this!

**Comment by alexsoble** [comment]
Closing this for now as AWS Ubuntu container support is not on the project roadmap
